bcp.exe ^
    boost/container/static_vector.hpp ^
    boost/context/detail/fcontext.hpp ^
    boost/icl/interval_set.hpp ^
    boost/functional/hash.hpp ^
    boost/icl/separate_interval_set.hpp ^
    boost/icl/interval.hpp ^
    boost/icl/interval_base_set.hpp ^
    boost/icl/interval_map.hpp ^
    boost/icl/split_interval_map.hpp ^
    boost/pool/pool.hpp ^
    boost/pool/pool_alloc.hpp ^
    boost/pool/poolfwd.hpp ^
    boost/heap/fibonacci_heap.hpp ^
    boost/asio.hpp ^
    boost/process/async_pipe.hpp ^
    boost/algorithm/string.hpp ^
    boost/container/flat_map.hpp ^
    boost/intrusive/rbtree.hpp ^
    boost/range/algorithm_ext/erase.hpp ^
    boost/container_hash/hash.hpp ^
    boost/crc.hpp ^
    boost/container/small_vector.hpp ^
    boost/algorithm/string/replace.hpp ^
    boost/container/static_vector.hpp ^
    boost/intrusive/list.hpp ^
    boost/intrusive/set.hpp ^
    boost/container/flat_set.hpp ^
    --boost="%1" .
